# Configuraci칩n del proyecto
project:
  name: "Mi Proyecto de Datos"
  version: "1.0.0"
  description: "An치lisis de datos con Python"

# Rutas de datos
data:
  raw: "data/raw/"
  processed: "data/processed/"
  external: "data/external/"
  interim: "data/interim/"

# Configuraci칩n de modelos
models:
  output_dir: "models/trained/"
  evaluation_dir: "models/evaluation/"

# Configuraci칩n de reportes
reports:
  figures_dir: "reports/figures/"
  output_dir: "reports/documents/"

# Logging
logging:
  level: "INFO"
  file: "logs/project.log"
